name: Publish Packages on NPM
on:
  workflow_dispatch:
    inputs:
      npmTag:
        description: 'NPM Tag'
        required: true
        default: 'latest'
jobs:
  publishing:
    name: Package Publishing
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: "https://registry.npmjs.org/"
          scope: "@vue-storefront"

    - name: Cache node_modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: yarn

    - name: Publish to NPM
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        echo "" >> .npmrc && echo "@vue-storefront:registry=https://registry.npmjs.org/" >> .npmrc
        yarn build:api-client && yarn publish:api-client "${{ github.event.inputs.npmTag }}" "$NPM_TOKEN"
        yarn build:composables && yarn publish:composables "${{ github.event.inputs.npmTag }}" "$NPM_TOKEN"

    - name: Checkout template repo
      uses: actions/checkout@v2
      with:
        repository: 'ForkPoint/vsf-sfcc-template'
        token: ${{ secrets.TEMPLATE_TOKEN }}
        path: './template'
        persist-credentials: false
        fetch-depth: 0

    - name: Update template
      run: |
        mv ./template/.git ${{ runner.temp }}/.vsf-tmpl-git
        yarn release:template
        mv ${{ runner.temp }}/.vsf-tmpl-git ./template/.git
        yarn --cwd ./template

    - name: Push updated template
      uses: ppavlov-dw/push@v1.2.1
      with:
        repository: 'ForkPoint/vsf-sfcc-template'
        github_token: ${{ secrets.TEMPLATE_TOKEN }}
        message: 'Update template'
        directory: './template'
